### ISSUE TITLE
waiting for agent to connect

### ISSUE THREAD

**Issue by kendinitekmeleyenkedi** [cloudradar-monitoring/plexus#10]
Hi,

I didn't have any problems with the installation steps, but I can't continue in the browser and agent connection section. What do we need to check? 

![image](https://user-images.githubusercontent.com/69451768/218687256-c011e62d-0315-43ff-985c-34f7c014c159.png)

Thanks.

**Comment by thorstenkramm** [comment]
@kendinitekmeleyenkedi Sorry for not having updated this repo.
Plexus is no longer supported. We are working on a "native" integration of a screen sharing integration into [RPort](https://github.com/cloudradar-monitoring/rport).
It's planned to be released in March or April 2023. [Subscribe to the release notes](https://subscribe.rport.io) to not miss it.
